linters-settings:
  lll:
    line-length: 200
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - lll
    - funlen
    - gosec
    - govet
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - revive
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace